server:
   port: 8000
   connection-timeout: 600000
   
spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/ees2019-api
      username: postgres
      password: postgres
      
   jpa:
      properties.hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
         show_sql: false
         format_sql: true 
   